import React from "react";

interface ResultCardProps {
  prediction: string;
  confidence: number;
}

const ResultCard: React.FC<ResultCardProps> = ({ prediction, confidence }) => {
  const confidencePercent = (confidence * 100).toFixed(1);
  const isHighConfidence = confidence >= 0.8;
  const isMediumConfidence = confidence >= 0.5 && confidence < 0.8;

  return (
    <div className="w-full rounded-lg border-2 border-border bg-card shadow-card overflow-hidden">
      <div className="gradient-medical px-5 py-3">
        <h3 className="text-sm font-semibold text-primary-foreground tracking-wide uppercase">
          Analysis Result
        </h3>
      </div>
      <div className="p-5 space-y-4">
        {/* Prediction Label */}
        <div>
          <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-1">
            Prediction
          </p>
          <p className="text-xl font-bold text-foreground">
            {prediction}
          </p>
        </div>

        {/* Confidence Score */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
              Confidence
            </p>
            <span
              className={`text-sm font-bold ${
                isHighConfidence
                  ? "text-success"
                  : isMediumConfidence
                  ? "text-warning"
                  : "text-destructive"
              }`}
            >
              {confidencePercent}%
            </span>
          </div>
          <div className="w-full h-2.5 bg-muted rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-500 ease-out ${
                isHighConfidence
                  ? "bg-success"
                  : isMediumConfidence
                  ? "bg-warning"
                  : "bg-destructive"
              }`}
              style={{ width: `${confidencePercent}%` }}
            />
          </div>
        </div>

        {/* Disclaimer */}
        <p className="text-xs text-muted-foreground leading-relaxed border-t border-border pt-3">
          This result is generated by an AI model and is intended for educational
          purposes only. Please consult a qualified dermatologist for medical
          advice.
        </p>
      </div>
    </div>
  );
};

export default ResultCard;
