# ============================================================
# app/services/report_service.py
# ============================================================

from typing import Tuple


def _condition_explanation(predicted_class: str) -> str:
    """Short dermatology-focused explanation per lesion type."""
    cls = (predicted_class or "").lower().strip()

    if cls == "melanoma":
        return (
            "Melanoma is a malignant skin cancer arising from melanocytes. "
            "It can grow rapidly and metastasize if not detected and treated early."
        )
    if cls == "nevus":
        return (
            "A melanocytic nevus (mole) is usually a benign cluster of pigment cells. "
            "Most nevi are harmless but should be monitored for ABCDE changes."
        )
    if cls == "basal_cell_carcinoma":
        return (
            "Basal cell carcinoma is the most common type of skin cancer. "
            "It tends to grow slowly and rarely metastasizes, but it can be locally destructive."
        )
    if cls == "actinic_keratosis":
        return (
            "Actinic keratosis is a sun-induced precancerous lesion that can progress "
            "to squamous cell carcinoma if left untreated."
        )
    if cls == "benign_keratosis":
        return (
            "Benign keratoses (such as seborrheic keratoses) are common, non-cancerous "
            "skin growths that typically require no treatment unless symptomatic."
        )
    if cls == "dermatofibroma":
        return (
            "Dermatofibroma is a benign fibrous nodule of the skin, often firm and "
            "dimpled, that rarely requires treatment."
        )
    if cls == "vascular_lesion":
        return (
            "Vascular lesions (such as hemangiomas) are benign proliferations of blood "
            "vessels and are usually harmless."
        )

    return (
        "The detected lesion type is not fully specified in the knowledge base. "
        "Clinical correlation by a dermatologist is recommended."
    )


def _action_from_risk_level(risk_level: str) -> str:
    level = (risk_level or "").lower().strip()

    if level == "high":
        return (
            "High risk: consult a dermatologist or skin cancer specialist immediately "
            "for full clinical assessment and possible biopsy."
        )
    if level == "medium":
        return (
            "Medium risk: schedule a dermatology appointment and monitor the lesion "
            "for changes in size, shape, color, or symptoms such as bleeding or itching."
        )
    return (
        "Low risk: continue routine skin self-examinations and maintain periodic "
        "dermatological check-ups, especially if you have additional risk factors."
    )


def generate_report(
    predicted_class: str,
    confidence: float,
    risk_level: str,
    risk_score: float | None = None,
) -> dict:
    """Generate a structured JSON medical-style report without requiring an LLM."""
    confidence_pct = round(float(confidence) * 100.0, 2)
    risk_expl = (
        f"The estimated risk level is **{risk_level.lower()}** based on the model's "
        f"probability for melanoma and related patterns."
    )

    explanation = (
        f"The AI model predicts **{predicted_class}** with a confidence of "
        f"approximately {confidence_pct}%. "
        f"{_condition_explanation(predicted_class)} "
        f"{risk_expl}"
    )

    recommended_action = _action_from_risk_level(risk_level)

    disclaimer = (
        "This report is generated by an AI system for informational purposes only and "
        "does not constitute a medical diagnosis. It must not replace evaluation by a "
        "qualified healthcare professional. Always consult a dermatologist or physician "
        "for clinical assessment and treatment decisions."
    )

    base_fields = {
        "predicted_class": predicted_class,
        "confidence": float(confidence),
        "risk_level": risk_level,
        "risk_score": risk_score,
        "explanation": explanation,
        "recommended_action": recommended_action,
        "disclaimer": disclaimer,
    }

    # Also provide a single combined text report for UIs that expect it.
    report_text = (
        f"Diagnosis: {predicted_class}\n"
        f"Confidence: {confidence_pct}%\n"
        f"Risk level: {risk_level}\n\n"
        f"{_condition_explanation(predicted_class)}\n\n"
        f"Recommended action: {recommended_action}\n\n"
        f"Disclaimer: {disclaimer}"
    )

    base_fields["report"] = report_text
    return base_fields